all:
	(cd ../po-uilib-201410012150; make $(MFLAGS) all)
	(cd ../poof-support-201410012150; make $(MFLAGS) all)
	(cd poof-core; make $(MFLAGS) all)
	(cd poof-textui; make $(MFLAGS) all)

clean:
	(cd poof-core; make $(MFLAGS) clean)
	(cd poof-textui; make $(MFLAGS) clean)
